apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hqpa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hqpa
    app.kubernetes.io/part-of: byoc-app-grrx
  name: hqpa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hqpa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hqpa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-mujl-tenant/byoc-app-grrx/hqpa@sha256:eb3b8b8759e8af8d96ccea1ae92ec125923d6d9d0a93358926fca1d2184dde2b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
